package com.mef.parkauto.entity;

public enum NatureMaintenance {
    VIDANGE,
    FILTRES,
    REVISION_PERIODIQUE,
    DISTRIBUTION,
    PNEUMATIQUES,
    FREINS,
    BATTERIE,
    CLIMATISATION,
    AMORTISSEURS_SUSPENSION,
    EMBRAYAGE_TRANSMISSION,
    INJECTION_TURBO,
    CIRCUIT_REFROIDISSEMENT,
    CARROSSERIE_PEINTURE,
    ECLAIRAGE_SIGNALISATION,
    PARE_BRISE_VITRAGE,
    REPARATION_PANNE,
    CONTROLE_TECHNIQUE,
    AUTRE
}
