# Context builder
import os, sys, json

sys.stdout.reconfigure(encoding='utf-8')
print('Context builder initialized')

def get_sprints():
    return {
        'S1': {'name': 'Sprint 1 — Initialisation Technique, Sécurité & Utilisateurs', 'dates': '13/07/2026 au 17/07/2026', 'sp': 34, 'objectives': ['Architecture socle Spring Boot 3.x / Java 17-25 + PostgreSQL/H2', 'Contrôle d accès RBAC stateless JWT (Access/Refresh Tokens)', 'CRUD Utilisateurs avec politique de mots de passe SHA-256 et forçage 1ère connexion', 'Traçabilité et journalisation d audit (JournalAction / AuditLog)'], 'rules': ['RG01: Unicité email et matricule', 'RG02: Hachage cryptographique SHA-256 avec sel', 'RG03: Forçage changement mot de passe (doitChangerMotDePasse=true)', 'RG04: Access Token (15 min), Refresh Token (7 j)', 'RG05: Audit trail systématique de toute mutation dans journal_actions']},
        'S2': {'name': 'Sprint 2 — Référentiel du Parc Automobile & Cycle de Vie Véhicules', 'dates': '20/07/2026 au 24/07/2026', 'sp': 42, 'objectives': ['Modélisation de 40+ attributs techniques, administratifs et d acquisition', 'Cycle de vie à 12 statuts administratifs et 8 états techniques', 'Historisation automatique des mutations dans historique_statuts_vehicule', 'Moteur de recherche multicritères paginé et exports'], 'rules': ['RG01: Unicité stricte Immatriculation, VIN (17 car.) et Inventaire MEF', 'RG02: Contrôle cohérence kilométrique croissante', 'RG03: Soft delete avec préservation historique', 'RG04: Transition dynamique des statuts sur événement métier']},
        'S3': {'name': 'Sprint 3 — Conducteurs, Demandes Déplacement, Affectations & Ordres OM', 'dates': '27/07/2026 au 31/07/2026', 'sp': 48, 'objectives': ['Référentiel des chauffeurs (permis, catégories, validité médicale)', 'Workflow d approbation à 2 niveaux (N1 Responsable -> N2 Gestionnaire)', 'Affectations véhicules et chauffeurs avec contrôle de disponibilité', 'Générateur d Ordre de Mission officiel PDF iText avec QR Code sécurisé', 'Module de restitution avec contrôle kilométrique et carburant retour'], 'rules': ['RG01: Validation permis et adéquation catégorie', 'RG02: Blocage si véhicule non DISPONIBLE ou conducteur non ACTIF', 'RG03: Validation N1 obligatoire avant affectation N2', 'RG04: Km retour >= Km départ', 'RG05: Ordre de mission PDF infalsifiable horodaté']},
        'S4': {'name': 'Sprint 4 — Suivi Carburant, Cartes Pétrolières & TCO Initial', 'dates': '03/08/2026 au 07/08/2026', 'sp': 38, 'objectives': ['Gestion du parc de cartes carburant (numéro masqué, plafonds mensuels)', 'Enregistrement des pleins et transactions carburant avec justificatifs', 'Calcul automatique consommation L/100km et détection surconsommations (+25%)', 'Initiation du calcul du coût global d exploitation (TCO)'], 'rules': ['RG01: Contrôle validité et solde carte carburant', 'RG02: Cohérence kilométrique lors du plein', 'RG03: Alerte surconsommation > moyenne + 25%', 'RG04: Rapprochement véhicule / carte']},
        'S5': {'name': 'Sprint 5 — Assurances Flotte, Sinistres, Visites, Taxes & Réforme', 'dates': '10/08/2026 au 14/08/2026', 'sp': 52, 'objectives': ['Gestion des contrats d assurance flotte (AXA, RMA, Wafa), garanties, primes, alertes J-30/J-7', 'Déclaration et instruction des sinistres avec GED (constats, photos)', 'Enregistrement des infractions radar et imputation au conducteur en mission', 'Visites techniques réglementaires et taxes automobiles (vignettes)', 'Procédure de déclassement, réforme et sortie d inventaire'], 'rules': ['RG01: Alertes proactives J-30 et J-7 expiration assurance/visite', 'RG02: Vérification assurance active pour tout sinistre', 'RG03: Imputation nominative des amendes au chauffeur en mission', 'RG04: Verrouillage des véhicules au statut REFORME']},
        'S6': {'name': 'Sprint 6 — Maintenance Préventive & Curative, Pannes & Garages Agréés', 'dates': '17/08/2026 au 21/08/2026', 'sp': 46, 'objectives': ['Planification des entretiens préventifs et alertes à 90% du seuil', 'Cycle de vie des pannes (Signalement -> Diagnostic -> Devis -> Réparation -> Clôture)', 'Référentiel des garages agréés MEF, catalogue pièces détachées, devis/factures', 'Mise à jour automatique état technique et immobilisation du véhicule'], 'rules': ['RG01: Basculement véhicule à IMMOBILISE/EN_MAINTENANCE', 'RG02: Km intervention >= Km dernier relevé', 'RG03: Calcul automatique prochaine échéance kilométrique', 'RG04: Validation devis si dépassement plafond délégation']},
        'S7': {'name': 'Sprint 7 — Contrôle Budgétaire Analytique, Tableaux de Bord & KPIs', 'dates': '24/08/2026 au 29/08/2026', 'sp': 54, 'objectives': ['Comptabilité budgétaire analytique (exercices, dotations par Direction MEF)', 'Chaîne des engagements financiers : Crédits Alloués -> Engagements -> Liquidations -> Reste', 'Alertes budgétaires préventives (80%) et critiques (95%)', 'Tableaux de bord multi-niveaux, calcul dynamique TCO, MAD/km et immobilisation', 'Génération des états financiers en PDF (iText) et Excel (Apache POI)'], 'rules': ['RG01: Contrôle budgétaire bloquant (Reste >= Montant engagé)', 'RG02: Imputation analytique stricte par nature de dépense', 'RG03: Alerte 80% jauge orange et 95% jauge rouge bloquante', 'RG04: TCO = Somme(Acq + Carburant + Maint + Assur + Taxes + Sinistres)']},
        'S8': {'name': 'Sprint 8 — Recette Globale UAT, Moteur Exports, Sécurité & Déploiement', 'dates': '31/08/2026 au 04/09/2026', 'sp': 40, 'objectives': ['Exécution de la recette UAT de bout en bout couvrant 100% du Cahier des Charges MEF', 'Moteur universel d exportation de données multi-formats (PDF officiel, Excel, CSV)', 'Durcissement sécurité, audit trail exhaustif, conformité CNDP/DGSSI', 'Optimisation performances backend (JPQL, index) et frontend Vite/React', 'Industrialisation du déploiement Docker Compose et plan PRA'], 'rules': ['RG01: 100% critères acceptation validés sans anomalie bloquante P1/P2', 'RG02: Conservation journaux audit 5 ans', 'RG03: Temps réponse API < 200ms à 95%', 'RG04: Charte graphique MEF sur 100% des exports']}
    }
