# -*- coding: utf-8 -*-
import json, os, sys
sys.stdout.reconfigure(encoding='utf-8')

# We will define the full structured text and export both .md and .json

lines = []
p = lines.append

p('# RAPPORT DE CONTEXTE HAUTE DENSITÉ — PARK AUTO MEF')
p('**Rôle :** Senior Context Optimization Engineer')
p('**Projet :** Système Intégré de Gestion du Parc Automobile du Ministère de l\'Économie et des Finances (Park Auto MEF)')
p('**Auteur :** EL KHATOURY Hassan (ENSA Al Hoceima / Ministère de l\'Économie et des Finances)')
p('**Encadrant Professionnel :** M. ELKAOUMI Aimad (Direction du Budget — MEF)')
p('**Date d\'Agrégation :** 27 Août 2026')
p('**Statut :** Référentiel Consolidé de Contexte Technique, Fonctionnel et Académique (Sprints 1 à 8)')
p('')
p('---')
p('')
p('## SOMMAIRE EXÉCUTIF')
p('')
p('Le présent référentiel à haute densité a été conçu et consolidé par un Senior Context Optimization Engineer afin de fournir une **source de vérité technique, méthodologique et fonctionnelle absolue** pour le projet **Park Auto MEF**.')
p('Il réalise une synthèse exhaustive à partir de l\'ensemble des sources primaires du projet :')
p('1. Les documents de planification et de spécification des **8 sprints hebdomadaires** (Sprints 1 à 8).')
p('2. Les rapports de revue et de livraison de chaque sprint (Sprints 2, 3, 4, 5, 6, 7, 8).')
p('3. Le code source réel de l\'application (**Spring Boot 3 / Java 17-25** en backend, **React 18 / Vite** en frontend).')
p('4. Le schéma de base de données relationnelle (**28 entités JPA persistantes, 16 énumérations métier, scripts Liquibase, base PostgreSQL**).')
p('5. Le catalogue des assets graphiques (**39 figures et diagrammes UML normalisés, 47 captures d\'écrans réelles**).')
p('6. L\'audit comparatif rigoureux face au rapport de référence d\'inspiration (*rapport_insperation.pdf*, 78 pages, modèle PFE d\'État).')
p('')
p('---')
p('')
p('## 1. FEUILLE DE ROUTE TECHNIQUE ET CHRONOLOGIE AGRÉGÉE (SPRINTS 1 À 8)')
p('')
p('Le développement a suivi le cadre méthodologique **Agile Scrum**, cadencé en **8 sprints hebdomadaires successifs** (durée totale : 8 semaines, du 13/07/2026 au 04/09/2026), cumulant une vélocité totale de **354 Story Points (SP)**.')
p('')
p('| Sprint | Périmètre & Désignation | Période Prévue | Vélocité | Composants Backend Clés | Vues Frontend Réalisées |')
p('| :--- | :--- | :--- | :--- | :--- | :--- |')
p('| **S1** | **Initialisation Technique & Sécurité RBAC** | 13/07 - 17/07 | 34 SP | Spring Security 6, JWT, User CRUD, Audit | LoginView, ForceChangePasswordModal |')
p('| **S2** | **Référentiel Flotte & Cycle de Vie Véhicules** | 20/07 - 24/07 | 42 SP | Vehicule, HistoriqueStatut, Soft Delete | VehiculesListView, VehiculeDetailView, VehiculeFormModal |')
p('| **S3** | **Chauffeurs, Demandes, Affectations & OM** | 27/07 - 31/07 | 48 SP | Conducteur, Demande, Affectation, iText OM | ConducteursView, DemandesView, AffectationsView |')
p('| **S4** | **Carburant, Cartes Pétrolières & TCO Initial** | 03/08 - 07/08 | 38 SP | CarteCarburant, PleinCarburant, Conso L/100 | CarburantView, CartesModal, PleinModal |')
p('| **S5** | **Assurances, Sinistres, Taxes & Réforme** | 10/08 - 14/08 | 52 SP | Assurance, Sinistre, Infraction, GED, Taxe | AssurancesView, SinistresView, VisitesTaxesReformeView |')
p('| **S6** | **Maintenance, Pannes & Garages Agréés** | 17/08 - 21/08 | 46 SP | PanneVehicule, Intervention, Pieces, Garage | MaintenanceView, PannesView, GaragesView |')
p('| **S7** | **Contrôle Budgétaire & Tableaux de Bord** | 24/08 - 29/08 | 54 SP | ExerciceBudgetaire, Budget, ReportingService | BudgetView, DashboardView, ReportingModal |')
p('| **S8** | **Recette UAT, Exports Massifs & Déploiement** | 31/08 - 04/09 | 40 SP | Universal Export Engine, Docker Compose, PRA | RapportsView, AuditView, ProfilView |')
p('| **TOTAL** | **8 Sprints de Réalisation Complète** | **8 Semaines** | **354 SP** | **28 Entités / 23 Services / 22 Controllers** | **17 Vues Métier / 4 Modales Principales** |')
p('')

p('### FICHE TECHNIQUE DÉTAILLÉE PAR SPRINT')
p('')
p('#### SPRINT 1 : Initialisation Technique, Sécurité RBAC & Gestion des Utilisateurs')
p('- **Période :** 13/07/2026 au 17/07/2026 | **Durée :** 5 jours ouvrés | **Vélocité :** 34 Story Points')
p('- **Objectifs :** Mise en place du socle applicatif Spring Boot 3 / Java 17-25, sécurité stateless par jetons JWT, gestion des 7 rôles du MEF, CRUD utilisateurs et journalisation d\'audit.')
p('- **Backlog MoSCoW :**')
p('  - *Must Have :* Authentification JWT (Access 15 min / Refresh 7 j), 7 rôles RBAC (ADMIN, GESTIONNAIRE_CENTRAL, GESTIONNAIRE_LOCAL, RESPONSABLE_FINANCIER, RESPONSABLE_SERVICE, CONDUCTEUR, CONSULTATION), Hachage SHA-256 avec sel, Statuts (ACTIVE, LOCKED, ARCHIVED).')
p('  - *Should Have :* Forçage de changement de mot de passe à la 1ère connexion (doitChangerMotDePasse = true), traçabilité JournalAction avec IP et timestamp.')
p('  - *Could Have :* Filtres utilisateurs par direction/service et pagination des comptes.')
p('- **Règles de Gestion Clés :**')
p('  - **RG01 :** Unicité stricte de l\'email et du matricule administratif.')
p('  - **RG02 :** Hachage cryptographique fort SHA-256 avec sel ou BCrypt (facteur 12).')
p('  - **RG03 :** Forçage immédiat du changement de mot de passe temporaire dès la 1ère connexion.')
p('  - **RG04 :** Access Token expiré = HTTP 401 déclenchant rafraîchissement silencieux via Refresh Token.')
p('  - **RG05 :** Piste d\'audit non altérable dans journal_actions pour toute écriture.')
p('- **Validation & Tests :** Tests unitaires Mockito sur AuthService, JwtService, UtilisateurService. Validation Swagger UI.')
p('')
p('#### SPRINT 2 : Référentiel du Parc Automobile & Cycle de Vie des Véhicules')
p('- **Période :** 20/07/2026 au 24/07/2026 | **Durée :** 5 jours ouvrés | **Vélocité :** 42 Story Points')
p('- **Objectifs :** Modélisation de la flotte (40+ attributs), gestion dynamique des 12 statuts administratifs et 8 états techniques, historisation automatique et recherche paginée.')
p('- **Backlog MoSCoW :**')
p('  - *Must Have :* CRUD Véhicule complet, 12 statuts (DISPONIBLE, AFFECTE, EN_MISSION, EN_MAINTENANCE, EN_PANNE, ACCIDENTE, EN_REPARATION, IMMOBILISE, EN_COURS_DE_REFORME, REFORME, VENDU, RESTITUE), 8 états techniques (EXCELLENT à SINISTRE_TOTAL), contrôle d\'unicité VIN/Immatriculation/Inventaire.')
p('  - *Should Have :* Table historique_statuts_vehicule, Soft delete (isDeleted = true), calcul automatique de l\'âge du véhicule.')
p('  - *Could Have :* Export de la liste en Excel, galerie photo du véhicule.')
p('- **Règles de Gestion Clés :**')
p('  - **RG01 :** Unicité absolue de l\'immatriculation marocaine, du VIN (17 car. ISO) et du numéro d\'inventaire MEF.')
p('  - **RG02 :** Cohérence kilométrique : Kilométrage actuel >= Kilométrage initial / dernier relevé.')
p('  - **RG03 :** Archivage logique (Soft delete) préservant l\'intégrité des affectations et factures passées.')
p('  - **RG04 :** Transition d\'état automatique sur action métier.')
p('- **Validation & Tests :** VehiculeServiceTest, validation des contraintes d\'intégrité et des filtres multicritères.')
p('')
p('#### SPRINT 3 : Conducteurs, Demandes de Déplacement, Affectations & Ordres de Mission')
p('- **Période :** 27/07/2026 au 31/07/2026 | **Durée :** 5 jours ouvrés | **Vélocité :** 48 Story Points')
p('- **Objectifs :** Référentiel conducteurs (permis, validité médicale), workflow d\'approbation à 2 niveaux (N1 Responsable -> N2 Gestionnaire), affectation de véhicule, génération Ordre de Mission PDF iText avec QR Code, contrôle retour.')
p('- **Backlog MoSCoW :**')
p('  - *Must Have :* Fiche conducteur (CIN, permis A/B/C/D, validité), Workflow Demande (EN_ATTENTE_VALIDATION, VALIDEE_SERVICE, APPROUVEE_AFFECTEE, REJETEE), Affectation avec contrôle de disponibilité, Générateur PDF officiel Ordre de Mission.')
p('  - *Should Have :* Restitution de véhicule avec saisie kilométrage et carburant retour, QR code de vérification sur l\'ordre de mission.')
p('  - *Could Have :* Notification email automatique au demandeur et au chauffeur.')
p('- **Règles de Gestion Clés :**')
p('  - **RG01 :** Permis de conduire valide à la date de mission et catégorie conforme au type de véhicule.')
p('  - **RG02 :** Véhicule obligatoirement DISPONIBLE et conducteur ACTIF pour valider une affectation.')
p('  - **RG03 :** Validation N1 préalable obligatoire avant l\'affectation opérationnelle N2.')
p('  - **RG04 :** Contrôle kilométrique retour (Km_retour >= Km_depart) et détection des sur-distances.')
p('  - **RG05 :** Ordre de mission PDF infalsifiable avec référence unique et horodatage certifié.')
p('- **Validation & Tests :** Tests d\'intégration du workflow de réservation, génération et vérification du binaire PDF iText.')
p('')
p('#### SPRINT 4 : Suivi Carburant, Cartes Pétrolières & Calcul du TCO Initial')
p('- **Période :** 03/08/2026 au 07/08/2026 | **Durée :** 5 jours ouvrés | **Vélocité :** 38 Story Points')
p('- **Objectifs :** Gestion des cartes carburant et vignettes, enregistrement des transactions de plein, algorithme de consommation moyenne L/100km, détection d\'anomalies de surconsommation, TCO initial.')
p('- **Backlog MoSCoW :**')
p('  - *Must Have :* Référentiel cartes pétrolières (fournisseur, plafond mensuel, solde), Saisie des pleins (litres, montant TTC, station, index km), Calcul automatique Conso = (Litres / Delta_Km) * 100.')
p('  - *Should Have :* Détection automatique des surconsommations (> moyenne constructeur + 25%), calcul TCO initial.')
p('  - *Could Have :* Tableau comparatif des consommations par marque et modèle.')
p('- **Règles de Gestion Clés :**')
p('  - **RG01 :** Carte carburant ACTIVE et montant du plein compatible avec le plafond mensuel restant.')
p('  - **RG02 :** Index kilométrique cohérent et strictement supérieur à l\'index du plein précédent.')
p('  - **RG03 :** Alerte surconsommation générée automatiquement au gestionnaire de flotte si seuil dépassé de 25%.')
p('  - **RG04 :** Rapprochement systématique véhicule / carte carburant assignée.')
p('- **Validation & Tests :** Tests unitaires du moteur de calcul kilométrique et des déclencheurs d\'alertes.')
p('')

p('#### SPRINT 5 : Assurances Flotte, Sinistres, Visites Techniques, Taxes & Réforme')
p('- **Période :** 10/08/2026 au 14/08/2026 | **Durée :** 5 jours ouvrés | **Vélocité :** 52 Story Points')
p('- **Objectifs :** Polices d\'assurance flotte (AXA, RMA, Wafa), garanties, primes, alertes J-30/J-7, gestion des sinistres (constats, photos GED, franchises, indemnisation), infractions radar, visites techniques et déclassement/réforme.')
p('- **Backlog MoSCoW :**')
p('  - *Must Have :* Suivi des polices d\'assurance avec alertes d\'expiration à J-30 et J-7, Déclaration de sinistre avec attachement GED, Imputation des infractions radar au chauffeur en mission, Suivi des visites techniques (favorable, contre-visite sous 15j) et vignettes.')
p('  - *Should Have :* Workflow de réforme de véhicule (EN_COURS_DE_REFORME, REFORME, VENDU) avec PV de commission.')
p('  - *Could Have :* Suivi des recours contre les compagnies d\'assurance adverses.')
p('- **Règles de Gestion Clés :**')
p('  - **RG01 :** Alerte automatique à J-30 et J-7 avant toute expiration de police d\'assurance ou de visite technique.')
p('  - **RG02 :** Police d\'assurance active obligatoire à la date de survenance de tout accident déclaré.')
p('  - **RG03 :** Rapprochement horaire de l\'infraction avec l\'ordre de mission pour imputation nominative du PV.')
p('  - **RG04 :** Blocage définitif de toute affectation dès le passage d\'un véhicule au statut de réforme.')
p('- **Validation & Tests :** Tests de notification des alertes d\'échéance et de stockage sécurisé GED.')
p('')
p('#### SPRINT 6 : Maintenance Préventive & Curative, Pannes & Garages Agréés')
p('- **Période :** 17/08/2026 au 21/08/2026 | **Durée :** 5 jours ouvrés | **Vélocité :** 46 Story Points')
p('- **Objectifs :** Planification des entretiens préventifs (vidanges, filtres, freins) avec alertes à 90% du seuil, cycle de vie complet des pannes et réparations en atelier agréé, gestion des pièces de rechange et main d\'œuvre.')
p('- **Backlog MoSCoW :**')
p('  - *Must Have :* Planification des révisions par seuil kilométrique, Signalement des pannes avec niveau d\'urgence (BLOQUANTE, MAJEURE, MINEURE), Workflow d\'intervention en garage agréé, Décomposition des coûts (pièces + main d\'œuvre).')
p('  - *Should Have :* Référentiel des garages conventionnés MEF, Bon de sortie d\'atelier et calcul de la prochaine échéance d\'entretien.')
p('  - *Could Have :* Historique des pièces détachées changées par véhicule.')
p('- **Règles de Gestion Clés :**')
p('  - **RG01 :** Véhicule basculé immédiatement à IMMOBILISE ou EN_MAINTENANCE dès l\'ouverture de réparation.')
p('  - **RG02 :** Km de l\'intervention >= Km du dernier relevé enregistré.')
p('  - **RG03 :** Recalcul automatique de la prochaine échéance (Km_prochain = Km_actuel + 10 000 km) à la clôture.')
p('  - **RG04 :** Validation financière obligatoire de tout devis dépassant le plafond de délégation.')
p('- **Validation & Tests :** Suite de tests unitaires et d\'intégration Sprint6MaintenancePanneSinistreTests (100% succès Surefire).')
p('')
p('#### SPRINT 7 : Contrôle Budgétaire Analytique, Tableaux de Bord & KPIs')
p('- **Période :** 24/08/2026 au 29/08/2026 | **Durée :** 6 jours ouvrés | **Vélocité :** 54 Story Points')
p('- **Objectifs :** Comptabilité budgétaire analytique (exercices fiscaux, dotations par Direction MEF), chaîne d\'engagements (Crédits -> Engagements -> Liquidations -> Reste), alertes budgétaires (80% / 95%), tableaux de bord décisionnels, TCO complet, coût MAD/km, exports financiers.')
p('- **Backlog MoSCoW :**')
p('  - *Must Have :* Lignes budgétaires par Direction et nature de dépense, Contrôle d\'engagement bloquant (Reste >= Montant), Alertes visuelles à 80% (orange) et 95% (rouge), Calcul dynamique du TCO et coût MAD/km, Dashboard analytique Recharts.')
p('  - *Should Have :* États financiers consolidés exportables en PDF (iText) et Excel (Apache POI), Taux d\'immobilisation de la flotte.')
p('  - *Could Have :* Prévisions budgétaires glissantes pour l\'exercice N+1.')
p('- **Règles de Gestion Clés :**')
p('  - **RG01 :** Rejet strict de tout engagement de dépense si le solde disponible de la ligne budgétaire est insuffisant.')
p('  - **RG02 :** Imputation analytique rigoureuse par nature de charge (CARBURANT, MAINTENANCE, ASSURANCE, TAXES, SINISTRES).')
p('  - **RG03 :** Déclenchement d\'alerte préventive à 80% et alerte critique avec blocage à 95% de consommation.')
p('  - **RG04 :** Calcul du TCO = Acquisition + Somme(Carburant) + Somme(Maintenance) + Somme(Assurances) + Somme(Taxes) + Somme(Sinistres).')
p('- **Validation & Tests :** Suite de tests d\'intégration Sprint7BudgetDashboardTests (100% succès Surefire).')
p('')
p('#### SPRINT 8 : Recette Globale UAT, Moteur d\'Exports Massifs, Sécurité & Déploiement')
p('- **Période :** 31/08/2026 au 04/09/2026 | **Durée :** 5 jours ouvrés | **Vélocité :** 40 Story Points')
p('- **Objectifs :** Recette fonctionnelle globale UAT couvrant 100% des exigences CdC MEF, moteur d\'exportation universel multi-formats (PDF officiel, Excel stylé, CSV), durcissement de la sécurité (Audit Trail, CNDP/DGSSI), optimisation des performances et conteneurisation Docker Compose.')
p('- **Backlog MoSCoW :**')
p('  - *Must Have :* Recette de bout en bout validée sans anomalie P1/P2, Moteur d\'exportation multi-formats dans ReportingService, Conteneurisation Docker Compose complète (Frontend Nginx, Backend Spring Boot, PostgreSQL, Redis).')
p('  - *Should Have :* Traçabilité d\'audit conservée sur 5 ans, Temps de réponse des API REST < 200 ms à 95%.')
p('  - *Could Have :* Documentation interactive Swagger OpenAPI 3.0 exportée en statique.')
p('- **Règles de Gestion Clés :**')
p('  - **RG01 :** 100% des scénarios de test UAT validés sans anomalie bloquante.')
p('  - **RG02 :** Conservation intègre et non altérable des journaux d\'audit.')
p('  - **RG03 :** Respect absolu de la charte graphique et du sceau institutionnel MEF sur tous les documents générés.')
p('- **Validation & Tests :** Campagne de recette globale UAT, validation de non-régression et qualification finale de production.')
p('')
